; ============================================================
;   PlatformIO-Konfiguration für alle M5Stick-Varianten
; ============================================================

[platformio]
default_envs = 
    esp32cam
    esp_wrover_kit

src_dir = .
include_dir = .

[common]
custom_flags =

custom_libs = 

; ------------------------------------------------------------
;   Gemeinsame Einstellungen für alle Boards
; ------------------------------------------------------------
[env]
platform = espressif32 @ 6.12.0

framework = arduino

platform_packages =

monitor_speed = 115200
lib_deps =

build_flags =

extra_scripts = 
    ; post:pio-scripts/output_bins.py


; ------------------------------------------------------------
;   AI Thinker ESP32-CAM
; ------------------------------------------------------------
[env:esp32cam]
board = esp32cam

board_build.partitions = huge_app.csv

platform_packages = 
    ${env.platform_packages}

build_flags =
    ${env.build_flags}
    ${common.custom_flags}
    -DRELEASE_NAME=\"ESP32-CAM\"
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

lib_deps =
    ${env.lib_deps}
    ${common.custom_libs}

lib_ignore = 
    ${env.lib_ignore}

extra_scripts = 
    ${env.extra_scripts}

; ------------------------------------------------------------
;   ESP WROVER KIT
; ------------------------------------------------------------
[env:esp_wrover_kit]
board = esp-wrover-kit

board_build.partitions = huge_app.csv

platform_packages = 
    ${env.platform_packages}

build_flags =
    ${env.build_flags}
    ${common.custom_flags}
    -DRELEASE_NAME=\"ESP32-WROVER-KIT\"
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

lib_deps =
    ${env.lib_deps}
    ${common.custom_libs}

lib_ignore = 
    ${env.lib_ignore}

extra_scripts = 
    ${env.extra_scripts}
